services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: chargeghar-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zaan5060
      - MYSQL_DATABASE=chargeghar_iot
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - iotdemo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pzaan5060"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # IoT Demo Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iotdemo-app
    ports:
      - "8080:8080"
    environment:
      # Redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=iotdemo123
      # MySQL connection
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=chargeghar_iot
      - DB_USERNAME=root
      - DB_PASSWORD=zaan5060
      # Application settings
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - iotdemo-network
    volumes:
      - app-logs:/usr/local/tomcat/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: iotdemo-redis
    command: >
      redis-server 
      --appendonly yes 
      --requirepass iotdemo123
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - iotdemo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iotdemo-network:
    driver: bridge
    name: iotdemo-network

volumes:
  mysql-data:
    name: chargeghar-mysql-data
  redis-data:
    name: iotdemo-redis-data
  app-logs:
    name: iotdemo-app-logs