services:
  # IoT Demo Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iotdemo-app
    ports:
      - "8080:8080"
    environment:
      # Redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=iotdemo123
      # Application settings
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - iotdemo-network
    volumes:
      - app-logs:/usr/local/tomcat/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: iotdemo-redis
    command: >
      redis-server 
      --appendonly yes 
      --requirepass iotdemo123
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - iotdemo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iotdemo-network:
    driver: bridge
    name: iotdemo-network

volumes:
  redis-data:
    name: iotdemo-redis-data
  app-logs:
    name: iotdemo-app-logs